#!/bin/bash
#this Script belong to Cloudaseem Youtube channel #####

# 1. jenkins installation on ubuntu 
sudo apt update -y
sleep 5
sudo apt install fontconfig openjdk-17-jre -y
sleep 15
sudo wget -O /usr/share/keyrings/jenkins-keyring.asc \
  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update -y
sleep 5
sudo apt-get install jenkins -y 
sleep 10
sudo systemctl enable jenkins
sudo systemctl start jenkins
sleep 10

# 2. Install Docker &  SONARQUBE  AS A CONTAINER IN THE EC2 INSTANCE
sudo apt-get update -y
sudo apt-get install docker.io -y
sleep 5
sudo usermod -aG docker ubuntu 
sudo usermod -aG docker jenkins 
newgrp docker
sleep 5
sudo chmod 777 /var/run/docker.sock

sleep 10
docker run -d --name sonar -p 9000:9000 sonarqube:lts-community
sleep 5

# 3. Install trivy ON THE INSTANCE
sudo apt-get install wget apt-transport-https gnupg lsb-release -y
sleep 5
wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
sudo apt-get update -y
sleep 5
sudo apt-get install trivy -y
sleep 5


# 4. Install Terraform

sudo apt install wget -y

wget https://releases.hashicorp.com/terraform/1.10.5/terraform_1.10.5_linux_amd64.zip
sleep 5
sudo apt install unzip -y  # Install unzip if not available
sleep 5
unzip terraform_1.10.5_linux_amd64.zip
sleep 5
sudo mv terraform /usr/local/bin/
sleep 5
terraform -v
sleep 5


# 5. Install kubectl
sudo apt update
sleep 5
sudo apt install curl -y
sleep 5
curl -LO https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl
sleep 5
sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
kubectl version --client

sleep 10

# 6. Install AWS CLI 
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
sleep 5
sudo apt-get install unzip -y
sleep 5
unzip awscliv2.zip
sudo ./aws/install

#7. eksctl installation 
curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
sleep 5
sudo mv /tmp/eksctl /usr/local/bin
sleep 5

#Status of installation
eksctl version
kubectl version --client
terraform -v
docker -version
aws --version
java --version
